import type {
	GetStaticProps,
	InferGetStaticPropsType,
	NextPage,
} from 'next';
import Head from 'next/head';
import ProductList from '../components/ProductList';
import { products } from '../products';

const Home: NextPage = ({
	products,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ProductList products={products} />
		</div>
	);
};

export default Home;

export const getStaticProps: GetStaticProps = async ({
	params,
}) => {
	const productsResponse = await products.lists();

	if (!productsResponse)
		return {
			notFound: true,
		};
	return {
		props: {
			products: productsResponse,
		},
	};
};
